global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'cadvisor'
    scrape_interval: 5s
    static_configs:
      - targets: ['cadvisor:8080']
    metrics_path: '/metrics'
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']